Setnet\JuanMarcetBundle\Entity\Banner:
  type: entity
  table: banner
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    imagen:
      type: text
      nullable: true
    descripcion:
      type: text
      nullable: true
    titulo:
      type: string
      length: 255
      nullable: true
    link:
      type: string
      length: 255
      nullable: true
    estado:
      type: integer
      nullable: true
    created:
      type: datetime
      nullable: true
    updated:
      type: datetime
      nullable: true
    tipo:
      type: string
      length: 50
      nullable: true
