Setnet\JuanMarcetBundle\Entity\DetalleEnvio:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: 255
      nullable: true
    calle:
      type: string
      length: 255
      nullable: true
    departamento:
      type: string
      length: 255
      nullable: true
    ciudad:
      type: string
      length: 100
      nullable: true
    provincia:
      type: string
      length: 100
      nullable: true
    region:
      type: string
      length: 100
      nullable: true
    codigo_postal:
      type: string
      length: 100
      nullable: true
  oneToOne:
    compra:
      targetEntity: Setnet\JuanMarcetBundle\Entity\Compra
      mappedBy: detalleEnvio
