Setnet\JuanMarcetBundle\Entity\Multimedia:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    tipo:
      type: string
      length: 10
      nullable: true
    url:
      type: text
      nullable: true
    descripcion:
      type: text
      nullable: true
    estado:
      type: integer
      nullable: true
    created:
      type: datetime
      nullable: true
    updated:
      type: datetime
      nullable: true
  oneToMany:
    imagenes:
      targetEntity: Setnet\JuanMarcetBundle\Entity\Imagenes
      mappedBy: multimedia
    videos:
      targetEntity: Setnet\JuanMarcetBundle\Entity\Videos
      mappedBy: multimedia
