Setnet\JuanMarcetBundle\Entity\Noticias:
  type: entity
  table: noticias
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    titulo:
      type: string
      length: 255
      nullable: true
    descripcion:
      type: text
      nullable: true
    created:
      type: datetime
      nullable: true
    updated:
      type: datetime
      nullable: true
    estado:
      type: integer
      nullable: true
    imagen:
      type: text
      nullable: true
    peso:
      type: integer
      nullable: true
