Setnet\JuanMarcetBundle\Entity\Tienda:
  type: entity
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: 255
      nullable: true
    direccion:
      type: string
      length: 255
      nullable: true
    telefono:
      type: string
      length: 255
      nullable: true
    email:
      type: string
      length: 255
      nullable: true
    atencion:
      type: string
      length: 255
      nullable: true
    created:
      type: datetime
      nullable: true
    updated:
      type: datetime
      nullable: true
    estado:
      type: integer
      nullable: true
    latitud:
      type: string
      length: 255
      nullable: true
    longuitud:
      type: string
      length: 255
      nullable: true
