parameters:
#    setnet_juan_marcet.example.class: Setnet\JuanMarcetBundle\Example

services:
#    setnet_juan_marcet.example:
#        class: %setnet_juan_marcet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
